In [2]:
import pandas as pd

In [3]:
data=pd.read_excel(r"C:\Users\centro.control\Documents\Python\Proyectos\Rutinas actuales vs frecuencia\excel final 1.xlsx")

In [4]:
data.head(2)

,Sitio,Operador,Área General,Área Específica,Actividades Detalladas,Necesidad por Hora,Turno Matutino,Turno Vespertino,Turno Nocturno,Turno Mixto,Tipo Limpieza,Zona,Técnica de Limpieza,Lunes,Martes,Miércoles,Jueves,Viernes,Sábado,Domingo
0,4E GLOBAL PLANTA,OPL 1,OFICINAS DE FINANZAS,NaN,"LIMPIEZA DE MOVILIARIO,BARRIDO ,TRAPEADO Y RET...",NaN,X,NaN,NaN,NaN,NORMAL,NaN,NaN,X,X,X,X,X,X,NaN
1,4E GLOBAL PLANTA,OPL 1,BAÑOS FINANZAS,NaN,"LAVADO Y DESINFECCION DE WC, MIGITORIO,LAVABOS...",NaN,X,NaN,NaN,NaN,CRITICA,NaN,NaN,X,X,X,X,X,X,NaN

In [5]:
# data.columns=data.iloc[0]
# data=data.drop(index=[0])
# data.reset_index(drop=True, inplace=True)
# data.head()

In [8]:
data_prueba= data.groupby(['Sitio','Turno Matutino','Turno Vespertino' ,'Turno Nocturno','Turno Mixto'])[['Lunes','Martes','Miércoles','Jueves','Viernes' ,'Sábado','Domingo']].first()
data_prueba

Empty DataFrame
Columns: [Lunes, Martes, Miércoles, Jueves, Viernes, Sábado, Domingo]
Index: []

In [ ]:
data_prueba=data_prueba.reset_index()
data_prueba

,Sitio,Turno Matutino,Turno Vespertino,Turno Nocturno,Turno Mixto
0,4E GLOBAL PLANTA,X,None,None,None
1,AMERICAN EXPRESS,X,X,X,None
2,AMERICAN EXPRESS POLANCO,X,X,X,None
3,ASSA ABLOY PELICANO,X,X,None,None
4,BELCORP CEDIS,X,X,None,None
5,CARGILL CORPORATIVO,X,X,None,None
6,COLEGIO ALEMAN PRIMARIA,X,X,None,None
7,COLEGIO MONTEVERDE,X,X,None,None
8,CORPORATIVO LIVERPOOL,X,X,None,None
9,CORPORATIVO TOKS,X,None,None,None
10,CUMBRES PRIMARIA Y KINDER,X,X,None,X
11,CUMBRES SECUNDARIA,X,None,None,X
12,EDGEWELL,X,X,None,None
13,ENCUENTRO OCEANIA,X,X,None,None
14,ERICSSON NEUCHATEL,X,None,None,None
15,EUROVI ACOXPA,X,X,X,None
16,EUROVI LA ROSA,X,None,None,None
17,EUROVI OASIS,X,X,X,None
18,FEMSA,X,X,None,X
19,INSTITUTO REGINA,X,None,None,X
20,KIMBERLY CLARK,None,None,None,X
21,LIVERPOOL CD JARDIN,X,X,None,None
22,LIVERPOOL COACALCO,X,X,None,None
23,LIVERPOOL INTERLOMAS,X,X,None,None
24,LIVERPOOL JILOTEPEC,X,None,X,None
25,LIVERPOOL LINDAVISTA,X,X,None,None
26,LIVERPOOL PERINORTE,X,X,None,None
27,LIVERPOOL TECAMAC,X,None,None,None
28,LIVERPOOL TEPEYAC,X,X,None,None
29,MAPFRE,X,X,None,None
30,MCCANN,X,X,None,None
31,MIYANA CENTRO COMERCIAL,X,X,None,None
32,MIYANA TORRE,X,X,None,None
33,NETFLIX,X,X,X,X
34,OXXO IZTACALCO,X,X,None,None
35,OXXO LOMAS VERDES,X,None,None,None
36,OXXO TECAMAC,X,X,None,None
37,PARQUE VIRREYES (AREAS COMUNES),X,X,None,X
38,PARQUES PLAZA NUEVO POLANCO,X,X,X,None
39,PLAY CITY ACOXPA,X,X,X,None
40,PLAY CITY ANTARA,X,X,X,None
41,PLAY CITY OASIS,X,X,X,None
42,PLAZA ARKANA NORTE,X,X,None,None
43,PLESA STEEL,X,None,None,X
44,PM STEEL,X,None,None,None
45,PROSA CHACHALACAS,X,None,None,None
46,PRUEBAS TECH2B,X,X,None,X
47,SIEMENS DOS PATIOS,X,None,None,None
48,SOFTTEK MITIKAH,X,X,None,None
49,SOFTTEK POLANCO,X,X,None,X
50,SOFTTEK TOREO,X,X,None,None
51,TELEMUNDO,X,X,None,X
52,TORRE ACUARIO,X,X,None,None
53,TORRE CHAPULTEPEC,X,X,None,None
54,TORRE REFORMA,X,X,None,None
55,TORRE VIRREYES,X,X,X,None
56,UNITED AIR LINES,X,X,X,X
57,UNIVERSAL PICTURES MEXICO,X,X,None,None
58,ZAGO EVEREST,X,None,None,None

In [ ]:
data_prueba = data_prueba.melt(id_vars=['Sitio'], var_name='Turno', value_name='Disponibilidad')

In [ ]:
orden_turnos = ['Turno Matutino', 'Turno Vespertino', 'Turno Nocturno', 'Turno Mixto']
data_prueba['Turno'] = pd.Categorical(data_prueba['Turno'], categories=orden_turnos, ordered=True)

In [ ]:
data_prueba = data_prueba.sort_values(ascending=True, by=['Sitio','Turno'])

In [ ]:
data_prueba

                         Sitio             Turno Disponibilidad
0             4E GLOBAL PLANTA    Turno Matutino              X
59            4E GLOBAL PLANTA  Turno Vespertino           None
118           4E GLOBAL PLANTA    Turno Nocturno           None
177           4E GLOBAL PLANTA       Turno Mixto           None
1             AMERICAN EXPRESS    Turno Matutino              X
..                         ...               ...            ...
234  UNIVERSAL PICTURES MEXICO       Turno Mixto           None
58                ZAGO EVEREST    Turno Matutino              X
117               ZAGO EVEREST  Turno Vespertino           None
176               ZAGO EVEREST    Turno Nocturno           None
235               ZAGO EVEREST       Turno Mixto           None

[236 rows x 3 columns]

In [ ]:
data.head(3)

,Sitio,Operador,Área General,Área Específica,Actividades Detalladas,Necesidad por Hora,Turno Matutino,Turno Vespertino,Turno Nocturno,Turno Mixto,Tipo Limpieza,Zona,Técnica de Limpieza,Lunes,Martes,Miércoles,Jueves,Viernes,Sábado,Domingo
0,4E GLOBAL PLANTA,OPL 1,OFICINAS DE FINANZAS,NaN,"LIMPIEZA DE MOVILIARIO,BARRIDO ,TRAPEADO Y RET...",NaN,X,NaN,NaN,NaN,NORMAL,NaN,NaN,X,X,X,X,X,X,NaN
1,4E GLOBAL PLANTA,OPL 1,BAÑOS FINANZAS,NaN,"LAVADO Y DESINFECCION DE WC, MIGITORIO,LAVABOS...",NaN,X,NaN,NaN,NaN,CRITICA,NaN,NaN,X,X,X,X,X,X,NaN
2,4E GLOBAL PLANTA,OPL 1,BAÑOS MUJERES /PLANTA,NaN,"LAVADO Y DESINFECCION DE WC,LAVABOS,PUERTAS Y ...",NaN,X,NaN,NaN,NaN,CRITICA,NaN,NaN,X,X,X,X,X,X,NaN

In [ ]:
datos=[]
for sitio in sitios:
    for turno in turnos:
        datos.append([sitio,turno])
datos

NameError: name 'sitios' is not defined

In [ ]:
datos=[]
for sitio in sitios:
    for turno in turnos:
        datos.append([sitio,turno, data.loc[data['Sitio'] == sitio ,'Lunes'].iloc[0],
                      data.loc[data['Sitio'] == sitio ,'Martes'].iloc[0],
                      data.loc[data['Sitio'] == sitio ,'Miércoles'].iloc[0],
                      data.loc[data['Sitio'] == sitio ,'Jueves'].iloc[0],
                      data.loc[data['Sitio'] == sitio ,'Viernes'].iloc[0],
                      data.loc[data['Sitio'] == sitio ,'Sábado'].iloc[0],
                      data.loc[data['Sitio'] == sitio ,'Domingo'].iloc[0]])
datos

NameError: name 'sitios' is not defined

In [ ]:
datos = []
for sitio in sitios:
    for turno in turnos:
        domingo = 'Domingo' if data.loc[data['Sitio'] == sitio, 'Domingo'].iloc[0] == 'X' else None
        datos.append([sitio, turno, domingo])
datos

[['4E GLOBAL PLANTA', 'Turno Matutino', None],
 ['4E GLOBAL PLANTA', 'Turno Vespertino', None],
 ['4E GLOBAL PLANTA', 'Turno Nocturno', None],
 ['4E GLOBAL PLANTA', 'Turno Mixto', None],
 ['AMERICAN EXPRESS', 'Turno Matutino', None],
 ['AMERICAN EXPRESS', 'Turno Vespertino', None],
 ['AMERICAN EXPRESS', 'Turno Nocturno', None],
 ['AMERICAN EXPRESS', 'Turno Mixto', None],
 ['CUMBRES PRIMARIA Y KINDER', 'Turno Matutino', None],
 ['CUMBRES PRIMARIA Y KINDER', 'Turno Vespertino', None],
 ['CUMBRES PRIMARIA Y KINDER', 'Turno Nocturno', None],
 ['CUMBRES PRIMARIA Y KINDER', 'Turno Mixto', None],
 ['CUMBRES SECUNDARIA', 'Turno Matutino', None],
 ['CUMBRES SECUNDARIA', 'Turno Vespertino', None],
 ['CUMBRES SECUNDARIA', 'Turno Nocturno', None],
 ['CUMBRES SECUNDARIA', 'Turno Mixto', None],
 ['EDGEWELL', 'Turno Matutino', None],
 ['EDGEWELL', 'Turno Vespertino', None],
 ['EDGEWELL', 'Turno Nocturno', None],
 ['EDGEWELL', 'Turno Mixto', None],
 ['ENCUENTRO OCEANIA', 'Turno Matutino', 'Domingo'],
 ['ENCUENTRO OCEANIA', 'Turno Vespertino', 'Domingo'],
 ['ENCUENTRO OCEANIA', 'Turno Nocturno', 'Domingo'],
 ['ENCUENTRO OCEANIA', 'Turno Mixto', 'Domingo'],
 ['ERICSSON NEUCHATEL', 'Turno Matutino', None],
 ['ERICSSON NEUCHATEL', 'Turno Vespertino', None],
 ['ERICSSON NEUCHATEL', 'Turno Nocturno', None],
 ['ERICSSON NEUCHATEL', 'Turno Mixto', None],
 ['EUROVI ACOXPA', 'Turno Matutino', 'Domingo'],
 ['EUROVI ACOXPA', 'Turno Vespertino', 'Domingo'],
 ['EUROVI ACOXPA', 'Turno Nocturno', 'Domingo'],
 ['EUROVI ACOXPA', 'Turno Mixto', 'Domingo'],
 ['EUROVI LA ROSA', 'Turno Matutino', 'Domingo'],
 ['EUROVI LA ROSA', 'Turno Vespertino', 'Domingo'],
 ['EUROVI LA ROSA', 'Turno Nocturno', 'Domingo'],
 ['EUROVI LA ROSA', 'Turno Mixto', 'Domingo'],
 ['EUROVI OASIS', 'Turno Matutino', 'Domingo'],
 ['EUROVI OASIS', 'Turno Vespertino', 'Domingo'],
 ['EUROVI OASIS', 'Turno Nocturno', 'Domingo'],
 ['EUROVI OASIS', 'Turno Mixto', 'Domingo'],
 ['FEMSA', 'Turno Matutino', None],
 ['FEMSA', 'Turno Vespertino', None],
 ['FEMSA', 'Turno Nocturno', None],
 ['FEMSA', 'Turno Mixto', None],
 ['INSTITUTO REGINA', 'Turno Matutino', None],
 ['INSTITUTO REGINA', 'Turno Vespertino', None],
 ['INSTITUTO REGINA', 'Turno Nocturno', None],
 ['INSTITUTO REGINA', 'Turno Mixto', None],
 ['AMERICAN EXPRESS POLANCO', 'Turno Matutino', None],
 ['AMERICAN EXPRESS POLANCO', 'Turno Vespertino', None],
 ['AMERICAN EXPRESS POLANCO', 'Turno Nocturno', None],
 ['AMERICAN EXPRESS POLANCO', 'Turno Mixto', None],
 ['KIMBERLY CLARK', 'Turno Matutino', None],
 ['KIMBERLY CLARK', 'Turno Vespertino', None],
 ['KIMBERLY CLARK', 'Turno Nocturno', None],
 ['KIMBERLY CLARK', 'Turno Mixto', None],
 ['LIVERPOOL CD JARDIN', 'Turno Matutino', 'Domingo'],
 ['LIVERPOOL CD JARDIN', 'Turno Vespertino', 'Domingo'],
 ['LIVERPOOL CD JARDIN', 'Turno Nocturno', 'Domingo'],
 ['LIVERPOOL CD JARDIN', 'Turno Mixto', 'Domingo'],
 ['LIVERPOOL COACALCO', 'Turno Matutino', 'Domingo'],
 ['LIVERPOOL COACALCO', 'Turno Vespertino', 'Domingo'],
 ['LIVERPOOL COACALCO', 'Turno Nocturno', 'Domingo'],
 ['LIVERPOOL COACALCO', 'Turno Mixto', 'Domingo'],
 ['LIVERPOOL INTERLOMAS', 'Turno Matutino', 'Domingo'],
 ['LIVERPOOL INTERLOMAS', 'Turno Vespertino', 'Domingo'],
 ['LIVERPOOL INTERLOMAS', 'Turno Nocturno', 'Domingo'],
 ['LIVERPOOL INTERLOMAS', 'Turno Mixto', 'Domingo'],
 ['LIVERPOOL JILOTEPEC', 'Turno Matutino', None],
 ['LIVERPOOL JILOTEPEC', 'Turno Vespertino', None],
 ['LIVERPOOL JILOTEPEC', 'Turno Nocturno', None],
 ['LIVERPOOL JILOTEPEC', 'Turno Mixto', None],
 ['LIVERPOOL LINDAVISTA', 'Turno Matutino', 'Domingo'],
 ['LIVERPOOL LINDAVISTA', 'Turno Vespertino', 'Domingo'],
 ['LIVERPOOL LINDAVISTA', 'Turno Nocturno', 'Domingo'],
 ['LIVERPOOL LINDAVISTA', 'Turno Mixto', 'Domingo'],
 ['LIVERPOOL PERINORTE', 'Turno Matutino', 'Domingo'],
 ['LIVERPOOL PERINORTE', 'Turno Vespertino', 'Domingo'],
 ['LIVERPOOL PERINORTE', 'Turno Nocturno', 'Domingo'],
 ['LIVERPOOL PERINORTE', 'Turno Mixto', 'Domingo'],
 ['LIVERPOOL TECAMAC', 'Turno Matutino', 'Domingo'],
 ['LIVERPOOL TECAMAC', 'Turno Vespertino', 'Domingo'],
 ['LIVERPOOL TECAMAC', 'Turno Nocturno', 'Domingo'],
 ['LIVERPOOL TECAMAC', 'Turno Mixto', 'Domingo'],
 ['LIVERPOOL TEPEYAC', 'Turno Matutino', 'Domingo'],
 ['LIVERPOOL TEPEYAC', 'Turno Vespertino', 'Domingo'],
 ['LIVERPOOL TEPEYAC', 'Turno Nocturno', 'Domingo'],
 ['LIVERPOOL TEPEYAC', 'Turno Mixto', 'Domingo'],
 ['MAPFRE', 'Turno Matutino', None],
 ['MAPFRE', 'Turno Vespertino', None],
 ['MAPFRE', 'Turno Nocturno', None],
 ['MAPFRE', 'Turno Mixto', None],
 ['ASSA ABLOY PELICANO', 'Turno Matutino', None],
 ['ASSA ABLOY PELICANO', 'Turno Vespertino', None],
 ['ASSA ABLOY PELICANO', 'Turno Nocturno', None],
 ['ASSA ABLOY PELICANO', 'Turno Mixto', None],
 ['MCCANN', 'Turno Matutino', None],
 ['MCCANN', 'Turno Vespertino', None],
 ['MCCANN', 'Turno Nocturno', None],
 ['MCCANN', 'Turno Mixto', None],
 ['MIYANA CENTRO COMERCIAL', 'Turno Matutino', 'Domingo'],
 ['MIYANA CENTRO COMERCIAL', 'Turno Vespertino', 'Domingo'],
 ['MIYANA CENTRO COMERCIAL', 'Turno Nocturno', 'Domingo'],
 ['MIYANA CENTRO COMERCIAL', 'Turno Mixto', 'Domingo'],
 ['MIYANA TORRE', 'Turno Matutino', None],
 ['MIYANA TORRE', 'Turno Vespertino', None],
 ['MIYANA TORRE', 'Turno Nocturno', None],
 ['MIYANA TORRE', 'Turno Mixto', None],
 ['NETFLIX', 'Turno Matutino', None],
 ['NETFLIX', 'Turno Vespertino', None],
 ['NETFLIX', 'Turno Nocturno', None],
 ['NETFLIX', 'Turno Mixto', None],
 ['OXXO IZTACALCO', 'Turno Matutino', None],
 ['OXXO IZTACALCO', 'Turno Vespertino', None],
 ['OXXO IZTACALCO', 'Turno Nocturno', None],
 ['OXXO IZTACALCO', 'Turno Mixto', None],
 ['OXXO LOMAS VERDES', 'Turno Matutino', None],
 ['OXXO LOMAS VERDES', 'Turno Vespertino', None],
 ['OXXO LOMAS VERDES', 'Turno Nocturno', None],
 ['OXXO LOMAS VERDES', 'Turno Mixto', None],
 ['OXXO TECAMAC', 'Turno Matutino', None],
 ['OXXO TECAMAC', 'Turno Vespertino', None],
 ['OXXO TECAMAC', 'Turno Nocturno', None],
 ['OXXO TECAMAC', 'Turno Mixto', None],
 ['PARQUE VIRREYES (AREAS COMUNES)', 'Turno Matutino', None],
 ['PARQUE VIRREYES (AREAS COMUNES)', 'Turno Vespertino', None],
 ['PARQUE VIRREYES (AREAS COMUNES)', 'Turno Nocturno', None],
 ['PARQUE VIRREYES (AREAS COMUNES)', 'Turno Mixto', None],
 ['PARQUES PLAZA NUEVO POLANCO', 'Turno Matutino', None],
 ['PARQUES PLAZA NUEVO POLANCO', 'Turno Vespertino', None],
 ['PARQUES PLAZA NUEVO POLANCO', 'Turno Nocturno', None],
 ['PARQUES PLAZA NUEVO POLANCO', 'Turno Mixto', None],
 ['PLAY CITY ACOXPA', 'Turno Matutino', 'Domingo'],
 ['PLAY CITY ACOXPA', 'Turno Vespertino', 'Domingo'],
 ['PLAY CITY ACOXPA', 'Turno Nocturno', 'Domingo'],
 ['PLAY CITY ACOXPA', 'Turno Mixto', 'Domingo'],
 ['BELCORP CEDIS', 'Turno Matutino', None],
 ['BELCORP CEDIS', 'Turno Vespertino', None],
 ['BELCORP CEDIS', 'Turno Nocturno', None],
 ['BELCORP CEDIS', 'Turno Mixto', None],
 ['PLAY CITY ANTARA', 'Turno Matutino', 'Domingo'],
 ['PLAY CITY ANTARA', 'Turno Vespertino', 'Domingo'],
 ['PLAY CITY ANTARA', 'Turno Nocturno', 'Domingo'],
 ['PLAY CITY ANTARA', 'Turno Mixto', 'Domingo'],
 ['PLAY CITY OASIS', 'Turno Matutino', 'Domingo'],
 ['PLAY CITY OASIS', 'Turno Vespertino', 'Domingo'],
 ['PLAY CITY OASIS', 'Turno Nocturno', 'Domingo'],
 ['PLAY CITY OASIS', 'Turno Mixto', 'Domingo'],
 ['PLAZA ARKANA NORTE', 'Turno Matutino', 'Domingo'],
 ['PLAZA ARKANA NORTE', 'Turno Vespertino', 'Domingo'],
 ['PLAZA ARKANA NORTE', 'Turno Nocturno', 'Domingo'],
 ['PLAZA ARKANA NORTE', 'Turno Mixto', 'Domingo'],
 ['PLESA STEEL', 'Turno Matutino', None],
 ['PLESA STEEL', 'Turno Vespertino', None],
 ['PLESA STEEL', 'Turno Nocturno', None],
 ['PLESA STEEL', 'Turno Mixto', None],
 ['PM STEEL', 'Turno Matutino', None],
 ['PM STEEL', 'Turno Vespertino', None],
 ['PM STEEL', 'Turno Nocturno', None],
 ['PM STEEL', 'Turno Mixto', None],
 ['PROSA CHACHALACAS', 'Turno Matutino', None],
 ['PROSA CHACHALACAS', 'Turno Vespertino', None],
 ['PROSA CHACHALACAS', 'Turno Nocturno', None],
 ['PROSA CHACHALACAS', 'Turno Mixto', None],
 ['PRUEBAS TECH2B', 'Turno Matutino', None],
 ['PRUEBAS TECH2B', 'Turno Vespertino', None],
 ['PRUEBAS TECH2B', 'Turno Nocturno', None],
 ['PRUEBAS TECH2B', 'Turno Mixto', None],
 ['SIEMENS DOS PATIOS', 'Turno Matutino', None],
 ['SIEMENS DOS PATIOS', 'Turno Vespertino', None],
 ['SIEMENS DOS PATIOS', 'Turno Nocturno', None],
 ['SIEMENS DOS PATIOS', 'Turno Mixto', None],
 ['SOFTTEK MITIKAH', 'Turno Matutino', None],
 ['SOFTTEK MITIKAH', 'Turno Vespertino', None],
 ['SOFTTEK MITIKAH', 'Turno Nocturno', None],
 ['SOFTTEK MITIKAH', 'Turno Mixto', None],
 ['SOFTTEK POLANCO', 'Turno Matutino', None],
 ['SOFTTEK POLANCO', 'Turno Vespertino', None],
 ['SOFTTEK POLANCO', 'Turno Nocturno', None],
 ['SOFTTEK POLANCO', 'Turno Mixto', None],
 ['CARGILL CORPORATIVO', 'Turno Matutino', None],
 ['CARGILL CORPORATIVO', 'Turno Vespertino', None],
 ['CARGILL CORPORATIVO', 'Turno Nocturno', None],
 ['CARGILL CORPORATIVO', 'Turno Mixto', None],
 ['SOFTTEK TOREO', 'Turno Matutino', None],
 ['SOFTTEK TOREO', 'Turno Vespertino', None],
 ['SOFTTEK TOREO', 'Turno Nocturno', None],
 ['SOFTTEK TOREO', 'Turno Mixto', None],
 ['TELEMUNDO', 'Turno Matutino', None],
 ['TELEMUNDO', 'Turno Vespertino', None],
 ['TELEMUNDO', 'Turno Nocturno', None],
 ['TELEMUNDO', 'Turno Mixto', None],
 ['TORRE ACUARIO', 'Turno Matutino', None],
 ['TORRE ACUARIO', 'Turno Vespertino', None],
 ['TORRE ACUARIO', 'Turno Nocturno', None],
 ['TORRE ACUARIO', 'Turno Mixto', None],
 ['TORRE CHAPULTEPEC', 'Turno Matutino', None],
 ['TORRE CHAPULTEPEC', 'Turno Vespertino', None],
 ['TORRE CHAPULTEPEC', 'Turno Nocturno', None],
 ['TORRE CHAPULTEPEC', 'Turno Mixto', None],
 ['TORRE REFORMA', 'Turno Matutino', None],
 ['TORRE REFORMA', 'Turno Vespertino', None],
 ['TORRE REFORMA', 'Turno Nocturno', None],
 ['TORRE REFORMA', 'Turno Mixto', None],
 ['TORRE VIRREYES', 'Turno Matutino', None],
 ['TORRE VIRREYES', 'Turno Vespertino', None],
 ['TORRE VIRREYES', 'Turno Nocturno', None],
 ['TORRE VIRREYES', 'Turno Mixto', None],
 ['UNITED AIR LINES', 'Turno Matutino', None],
 ['UNITED AIR LINES', 'Turno Vespertino', None],
 ['UNITED AIR LINES', 'Turno Nocturno', None],
 ['UNITED AIR LINES', 'Turno Mixto', None],
 ['UNIVERSAL PICTURES MEXICO', 'Turno Matutino', None],
 ['UNIVERSAL PICTURES MEXICO', 'Turno Vespertino', None],
 ['UNIVERSAL PICTURES MEXICO', 'Turno Nocturno', None],
 ['UNIVERSAL PICTURES MEXICO', 'Turno Mixto', None],
 ['ZAGO EVEREST', 'Turno Matutino', None],
 ['ZAGO EVEREST', 'Turno Vespertino', None],
 ['ZAGO EVEREST', 'Turno Nocturno', None],
 ['ZAGO EVEREST', 'Turno Mixto', None],
 ['COLEGIO ALEMAN PRIMARIA', 'Turno Matutino', None],
 ['COLEGIO ALEMAN PRIMARIA', 'Turno Vespertino', None],
 ['COLEGIO ALEMAN PRIMARIA', 'Turno Nocturno', None],
 ['COLEGIO ALEMAN PRIMARIA', 'Turno Mixto', None],
 ['COLEGIO MONTEVERDE', 'Turno Matutino', None],
 ['COLEGIO MONTEVERDE', 'Turno Vespertino', None],
 ['COLEGIO MONTEVERDE', 'Turno Nocturno', None],
 ['COLEGIO MONTEVERDE', 'Turno Mixto', None],
 ['CORPORATIVO LIVERPOOL', 'Turno Matutino', None],
 ['CORPORATIVO LIVERPOOL', 'Turno Vespertino', None],
 ['CORPORATIVO LIVERPOOL', 'Turno Nocturno', None],
 ['CORPORATIVO LIVERPOOL', 'Turno Mixto', None],
 ['CORPORATIVO TOKS', 'Turno Matutino', None],
 ['CORPORATIVO TOKS', 'Turno Vespertino', None],
 ['CORPORATIVO TOKS', 'Turno Nocturno', None],
 ['CORPORATIVO TOKS', 'Turno Mixto', None]]

In [ ]:
sitios = data['Sitio'].unique()
turnos = ['Turno Matutino', 'Turno Vespertino', 'Turno Nocturno', 'Turno Mixto']
dias = ['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo']
resultados = []

In [ ]:
for sitio in sitios:
    for turno in turnos:
        for dia in dias:
            if data.loc[data['Sitio'] == sitio, dia][0]:
                resultados=resultados.append(['sitio','turno','dia'])
            else: pass

AttributeError: 'NoneType' object has no attribute 'append'

In [ ]:
resultados

[]